name: '📁 Normalize Path'
description: 'Normalizes a file path according to the runner OS and provides both relative and absolute formats'
author: 'Francois Raminosona'

inputs:
  path:
    description: 'Path to normalize (can be relative or absolute)'
    required: true
  show-summary:
    description: 'Whether to show the action summary'
    required: false
    default: 'false'

outputs:
  normalized:
    description: 'Normalized path adjusted for the current OS'
    value: ${{ steps.normalize-path.outputs.normalized }}
  absolute:
    description: 'Absolute path resolved from the normalized path'
    value: ${{ steps.normalize-path.outputs.absolute }}
  exists:
    description: 'Whether the normalized path exists on the filesystem'
    value: ${{ steps.normalize-path.outputs.exists }}

runs:
  using: "composite"
  steps:
    # ================== ℹ️ ==================

    - name: "ℹ️ Gather environment information"
      shell: bash
      run: |
        echo "::group::ℹ️ Environment Information"
        echo "::debug::Operating System: $(uname -a)"
        echo "::debug::GitHub Runner OS: $RUNNER_OS"
        echo "::debug::GitHub Runner Version: $RUNNER_VERSION"
        echo "::debug::Shell: $SHELL"
        echo "::debug::OS Type: $OSTYPE"
        echo "::endgroup::"

    # ================== ✅ ==================

    - name: "✅ Validate inputs"
      shell: bash
      run: |
        echo "::group::🔍 Input Validation"
        echo "::debug::Validating inputs for path normalization"

        # Validate required parameters
        if [ -z "${{ inputs.path }}" ]; then
          echo "::error::Path parameter cannot be empty"
          exit 1
        fi

        # Check for potentially dangerous paths
        if [[ "${{ inputs.path }}" == *".."* ]]; then
          echo "::warning::Path contains parent directory references (..), ensure this is intentional"
        fi

        # Check for reserved characters on Windows
        if [[ "${{ runner.os }}" == "Windows" ]]; then
          INPUT_PATH="${{ inputs.path }}"
          if [[ "$INPUT_PATH" == *"<"* ]] || [[ "$INPUT_PATH" == *">"* ]] || [[ "$INPUT_PATH" == *":"* ]] || [[ "$INPUT_PATH" == *"\""* ]] || [[ "$INPUT_PATH" == *"|"* ]] || [[ "$INPUT_PATH" == *"?"* ]] || [[ "$INPUT_PATH" == *"*"* ]]; then
            echo "::warning::Path contains characters that may be invalid on Windows"
          fi
        fi

        echo "::notice::Input validation completed successfully"
        echo "::debug::Path to normalize: ${{ inputs.path }}"
        echo "::endgroup::"

    # ================== 🚀 ==================

    - name: "🔧 Normalize path"
      id: normalize-path
      shell: bash
      run: |
        echo "::group::🚀 Normalizing path"
        echo "::debug::Processing path normalization for: ${{ inputs.path }}"

        INPUT_PATH="${{ inputs.path }}"

        # Convert path separators based on OS
        if [[ "$OSTYPE" == "msys" || "$OSTYPE" == "win32" || "$OSTYPE" == "cygwin" ]]; then
          # Windows: convert forward slashes to backslashes
          NORMALIZED=$(echo "$INPUT_PATH" | sed 's|/|\\|g')
        else
          # Unix: convert backslashes to forward slashes
          NORMALIZED=$(echo "$INPUT_PATH" | sed 's|\\|/|g')
        fi

        # Remove redundant slashes and resolve . and ..
        # Use realpath if available, otherwise use a simpler approach
        if command -v realpath &> /dev/null; then
          if [ -e "$NORMALIZED" ]; then
            ABSOLUTE=$(realpath "$NORMALIZED" 2>/dev/null || echo "$PWD/$NORMALIZED")
            EXISTS="true"
          else
            ABSOLUTE="$PWD/$NORMALIZED"
            EXISTS="false"
          fi
        else
          # Fallback: construct absolute path manually
          if [[ "$NORMALIZED" == /* ]] || [[ "$NORMALIZED" == ?:* ]]; then
            ABSOLUTE="$NORMALIZED"
          else
            ABSOLUTE="$PWD/$NORMALIZED"
          fi

          if [ -e "$NORMALIZED" ]; then
            EXISTS="true"
          else
            EXISTS="false"
          fi
        fi

        # Normalize the path (remove ./ and resolve ..)
        NORMALIZED=$(echo "$NORMALIZED" | sed 's|^\./||' | sed 's|/\./|/|g')

        # Set outputs
        echo "normalized=$NORMALIZED" >> $GITHUB_OUTPUT
        echo "absolute=$ABSOLUTE" >> $GITHUB_OUTPUT
        echo "exists=$EXISTS" >> $GITHUB_OUTPUT

        echo "::notice::Path normalization completed successfully"
        echo "::debug::Normalized: $NORMALIZED"
        echo "::debug::Absolute: $ABSOLUTE"
        echo "::debug::Exists: $EXISTS"
        echo "::endgroup::"

    # ================== 🔍 ===================

    - name: "🔍 Verify normalization results"
      shell: bash
      run: |
        echo "::group::🔍 Verifying Normalization Results"

        # Verify that normalized output was generated
        if [ -z "${{ steps.normalize-path.outputs.normalized }}" ]; then
          echo "::error::Normalization failed - no normalized path generated"
          exit 1
        fi

        # Verify that absolute path was generated
        if [ -z "${{ steps.normalize-path.outputs.absolute }}" ]; then
          echo "::error::Normalization failed - no absolute path generated"
          exit 1
        fi

        # Verify exists output is boolean
        EXISTS_VALUE="${{ steps.normalize-path.outputs.exists }}"
        if [ "$EXISTS_VALUE" != "true" ] && [ "$EXISTS_VALUE" != "false" ]; then
          echo "::error::Invalid exists value: $EXISTS_VALUE (should be true or false)"
          exit 1
        fi

        echo "::notice::Path normalization verification completed successfully"
        echo "::debug::Verified normalized path: ${{ steps.normalize-path.outputs.normalized }}"
        echo "::debug::Verified absolute path: ${{ steps.normalize-path.outputs.absolute }}"
        echo "::debug::Verified exists status: ${{ steps.normalize-path.outputs.exists }}"
        echo "::endgroup::"

    # ================== 🔍 ===================
    - name: "🔍 Action Summary"
      if: always() && inputs.show-summary == 'true'
      shell: bash
      run: |
        cat >> $GITHUB_STEP_SUMMARY << 'EOF'
        <details><summary>Expand for details - 📊 Path Normalization Summary</summary>

        ## 🔧 Input Parameters
        | Parameter | Value |
        |-----------|-------|
        | 📁 Original Path | `${{ inputs.path }}` |
        | 🖥️ Runner OS | `${{ runner.os }}` |

        ## 📤 Normalization Results
        | Metric | Value |
        |--------|-------|
        | 📁 Normalized Path | `${{ steps.normalize-path.outputs.normalized }}` |
        | 🎯 Absolute Path | `${{ steps.normalize-path.outputs.absolute }}` |
        | ✅ Path Exists | `${{ steps.normalize-path.outputs.exists }}` |
        | 🔧 Status | `${{ steps.normalize-path.outcome }}` |

        ## ⚙️ Process Details
        | Step | Status |
        |------|--------|
        | ✅ Input Validation | `✅ Completed` |
        | 🔧 Path Normalization | `${{ steps.normalize-path.outcome == 'success' && '✅ Completed' || '❌ Failed' }}` |

        ## 📋 Path Analysis
        - **Original**: `${{ inputs.path }}`
        - **Normalized**: `${{ steps.normalize-path.outputs.normalized }}`
        - **Absolute**: `${{ steps.normalize-path.outputs.absolute }}`
        - **Exists**: ${{ steps.normalize-path.outputs.exists == 'true' && '✅ Yes' || '❌ No' }}

        </details>
        EOF

branding:
  icon: 'folder'
  color: 'blue'
