name: "ðŸŒ³ Debug Directory Tree"
description: "Simple directory tree display for debugging"
author: "Francois Raminosona"

inputs:
  path:
    description: "Path to display"
    required: false
    default: "."
  depth:
    description: "Maximum depth (0 for unlimited)"
    required: false
    default: "5"
  show-hidden:
    description: "Show hidden files"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:

    # ================== ðŸ“ ==================

    - name: "ðŸ“ Normalize path"
      id: normalize-path
      uses: laerdal/github_actions/normalize-path@main
      with:
        path: ${{ inputs.path }}

    # ================== âœ… ==================

    - name: "âœ… Validate input : booleans"
      shell: bash
      run: |
        for param in show-hidden; do
          case $param in
            show-hidden) value="${{ inputs.show-hidden }}" ;;
          esac
          if [ -n "$value" ] && [ "$value" != "true" ] && [ "$value" != "false" ]; then
            echo "::error::Parameter $param must be 'true' or 'false', got: $value"
            exit 1
          fi
        done

    - name: "âœ… Validate input : depth"
      shell: bash
      run: |
        if ! [[ "${{ inputs.depth }}" =~ ^[0-9]+$ ]]; then
          echo "::error::Depth must be a non-negative integer, got: ${{ inputs.depth }}"
          exit 1
        fi

    # ================== ðŸš€ ==================

    - name: "ðŸŒ³ Show directory tree"
      shell: bash
      run: |
        path="${{ inputs.path }}"
        depth="${{ inputs.depth }}"
        show_hidden="${{ inputs.show-hidden }}"

        echo "ï¿½ Directory tree for: $path"
        echo ""

        # Try tree command first
        if command -v tree >/dev/null 2>&1; then
          args=""

          if [ "$depth" != "0" ]; then
            args="$args -L $depth"
          fi

          if [ "$show_hidden" = "true" ]; then
            args="$args -a"
          fi

          tree $args "$path"
        else
          # Fallback to find
          find_args="$path"

          if [ "$depth" != "0" ]; then
            find_args="$find_args -maxdepth $depth"
          fi

          if [ "$show_hidden" = "false" ]; then
            find_args="$find_args ! -path '*/.*'"
          fi

          find $find_args | sort
        fi

branding:
  icon: "folder"
  color: "green"
