name: '🛠 Normalize Arguments'
description: 'Normalizes multi-line or single-line arguments into a clean, single-line string by joining lines with a separator'
author: 'Francois Raminosona'

inputs:
  arguments:
    description: 'Arguments to normalize (supports single-line, multi-line with |, or folded with >) - can be empty'
    required: false
    default: ''
  separator:
    description: 'Separator to use between lines (default: space)'
    required: false
    default: ' '
  show-summary:
    description: 'Whether to show the action summary'
    required: false
    default: 'false'

outputs:
  normalized-arguments:
    description: 'The normalized arguments as a single line'
    value: ${{ steps.normalize.outputs.normalized-arguments }}

runs:
  using: "composite"
  steps:
    - name: "✅ Validate inputs"
      shell: bash
      run: |
        echo "::group::🔍 Input Validation"
        echo "::debug::Validating inputs for argument normalization"

        # Validate boolean parameters
        case "${{ inputs.show-summary }}" in
          true|false) ;;
          *) echo "::error::show-summary must be 'true' or 'false'"; exit 1 ;;
        esac

        echo "::notice::Input validation completed successfully"
        echo "::endgroup::"

    - name: "🔧 Normalize Arguments"
      id: normalize
      shell: bash
      run: |
        echo "::group::🚀 Normalizing Arguments"
        echo "::debug::Starting argument normalization process"

        # Get the input arguments and separator
        ARGS="${{ inputs.arguments }}"
        SEPARATOR="${{ inputs.separator }}"

        # Handle empty arguments case
        if [ -z "$ARGS" ]; then
          echo "::debug::Empty arguments provided, returning empty result"
          echo "normalized-arguments=" >> $GITHUB_OUTPUT
          echo "::notice::Argument normalization completed (empty input)"
          echo "::endgroup::"
          exit 0
        fi

        # Simple approach: replace all newlines with spaces, then clean up
        # Use printf to avoid echo adding trailing newline
        NORMALIZED_ARGS=$(printf '%s' "$ARGS" | tr '\n' ' ' | tr -s ' ' | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')

        # If a custom separator is specified (not space), replace spaces with the separator
        if [ "$SEPARATOR" != " " ]; then
          NORMALIZED_ARGS=$(printf '%s' "$NORMALIZED_ARGS" | sed "s/ /$SEPARATOR/g")
        fi

        # Set outputs - use delimiter to handle any special characters safely
        delimiter="$(openssl rand -hex 16)"
        {
          echo "normalized-arguments<<${delimiter}"
          printf '%s' "$NORMALIZED_ARGS"
          echo ""
          echo "${delimiter}"
        } >> "$GITHUB_OUTPUT"

        echo "::notice::Argument normalization completed successfully"
        echo "::debug::Normalized arguments: $NORMALIZED_ARGS"
        echo "::endgroup::"

    - name: "📊 Action Summary"
      if: always() && inputs.show-summary == 'true'
      shell: bash
      run: |
        cat >> $GITHUB_STEP_SUMMARY << 'EOF'
        <details><summary>Expand for details - 📊 Normalize Arguments Summary</summary>

        ## 🔧 Input Parameters
        | Parameter | Value |
        |-----------|-------|
        | 📝 Arguments | `${{ inputs.arguments }}` |
        | 🔗 Separator | `${{ inputs.separator }}` |

        ## 📤 Normalization Results
        | Metric | Value |
        |--------|-------|
        | 🎯 Normalized Arguments | `${{ steps.normalize.outputs.normalized-arguments }}` |
        | ✅ Status | `${{ steps.normalize.outcome }}` |

        ## ⚙️ Process Details
        | Step | Status |
        |------|--------|
        | ✅ Input Validation | `✅ Completed` |
        | 🔧 Argument Normalization | `${{ steps.normalize.outcome == 'success' && '✅ Completed' || '❌ Failed' }}` |

        ## 📋 Usage Example
        ```yaml
        - name: "Build with normalized arguments"
          run: |
            dotnet build ${{ steps.normalize.outputs.normalized-arguments }}
        ```

        </details>
        EOF

branding:
  icon: 'settings'
  color: 'blue'
